export type SeoGuide = {
  slug: string;
  query: string;
  title: string;
  description: string;
  summary: string;
  points: string[];
};

export const SEO_GUIDES: SeoGuide[] = [
  {
    slug: "why-is-my-resume-not-getting-interviews",
    query: "why is my resume not getting interviews",
    title: "Why Is My Resume Not Getting Interviews?",
    description: "Find practical reasons a qualified candidate's resume may not lead to interviews, from formatting and keywords to unclear achievements.",
    summary: "Being qualified is not always enough if your resume does not make the fit obvious during a quick first scan. Use a repeatable checklist before sending the next application.",
    points: ["Check whether the format is easy to parse and skim.", "Match accurate keywords from the job description.", "Rewrite bullets around quantified results instead of responsibilities.", "Use a checklist rather than guessing why an application stalled."],
  },
  {
    slug: "applied-100-jobs-no-response",
    query: "applied to 100 jobs no response",
    title: "Applied to 100 Jobs and Got No Response? What to Check",
    description: "Learn why sending many applications may not produce responses and how targeted, tailored applications can reveal what is holding your search back.",
    summary: "A high application count does not guarantee visibility. Look for patterns in targeting, tailoring, seniority, job quality, and resume matching before increasing volume.",
    points: ["Check whether the resume is being filtered by the job's keywords and format requirements.", "Tailor each application instead of sending one generic version everywhere.", "Confirm the role matches your actual seniority and experience.", "Watch for stale or low-quality postings, including possible ghost jobs.", "Track applications, versions, match scores, and responses to find patterns."],
  },
  {
    slug: "resume-rejected-reasons",
    query: "reasons resume gets rejected",
    title: "Why Resumes Get Rejected: 5 Common Reasons",
    description: "Review the most common resume rejection causes, including keyword mismatch, parsing problems, vague bullets, missing qualifications, and generic tailoring.",
    summary: "A rejection does not identify one certain cause, but recurring resume problems are often diagnosable. Start with the requirements in the specific job description.",
    points: ["Keyword match is weak for the target posting.", "Tables, columns, or graphics may cause parsing problems.", "Bullets describe duties without measurable results.", "Required qualifications are missing or hard to find.", "The resume is too generic for the role."],
  },
  {
    slug: "no-response-after-applying-online",
    query: "no response after applying for job online",
    title: "No Response After Applying Online? What to Review",
    description: "Understand why online applications can disappear in high-volume queues and how precise instructions and job-specific keywords improve visibility.",
    summary: "Online portals often receive more applications than a recruiter can review closely. Make the application easy to route, search, and evaluate.",
    points: ["Follow every application instruction exactly.", "Use the job description's accurate terminology in your resume.", "Make contact details and core qualifications easy to locate.", "Keep a record of the version submitted and follow up professionally when appropriate."],
  },
  {
    slug: "resume-not-getting-shortlisted",
    query: "resume not getting shortlisted",
    title: "Why Your Resume Is Not Getting Shortlisted",
    description: "Learn how keyword visibility, standard headings, and quantified achievements affect whether a resume makes it to a shortlist.",
    summary: "Shortlisting depends on how clearly the resume exposes relevant skills and evidence, not only on whether you have done similar work.",
    points: ["Match skills to the exact role and job description.", "Use standard section headings so both software and people can find information.", "Lead bullets with outcomes, scale, and measurable results.", "Rescan the tailored version before submitting it."],
  },
  {
    slug: "why-good-resume-not-getting-calls",
    query: "good resume not getting calls",
    title: "Why a Good Resume May Not Be Getting Calls",
    description: "A polished resume can still miss calls when creative formatting or job-specific keyword gaps reduce its visibility during screening.",
    summary: "Design quality and screening quality are different tests. A resume can look impressive while its text order or terminology makes the fit harder to detect.",
    points: ["Check tables, columns, graphics, and other layouts that may cause parsing problems.", "Match accurate keywords to each job description instead of relying on general wording.", "Put the most relevant evidence near the top and in the first bullets.", "Run a separate check for every materially different role."],
  },
  {
    slug: "resume-ignored-by-recruiters",
    query: "resume being ignored by recruiters",
    title: "Why Recruiters May Be Ignoring Your Resume",
    description: "Improve the first-scan visibility of your resume with relevant keywords, strong results, and a version tailored to each role.",
    summary: "Initial reviews are often quick. Make the first few lines answer three questions: what role you fit, which relevant capabilities you bring, and what results you have delivered.",
    points: ["Lead with relevant keywords and outcomes, not a generic objective.", "Tailor the summary and first bullets to the role.", "Replace vague responsibility statements with evidence and scale.", "Keep formatting clean enough to skim and parse."],
  },
  {
    slug: "job-search-no-callbacks-fix",
    query: "job search no callbacks what to do",
    title: "No Callbacks in Your Job Search? A Practical Fix",
    description: "Use application tracking, resume match scores, targeted follow-ups, and better tailoring to diagnose a job search with few callbacks.",
    summary: "Treat the search like a small feedback loop. Track what you send, where you send it, and which version produces responses before changing everything at once.",
    points: ["Track resume version, job board, role, and match score per application.", "Look for patterns by role, seniority, industry, and source.", "Send a short, relevant follow-up about a week after applying when appropriate.", "Prioritize quality and targeting over raw application volume."],
  },
  {
    slug: "does-my-resume-pass-ats-test",
    query: "does my resume pass ats",
    title: "Does My Resume Pass an ATS Test? How to Check",
    description: "Learn a practical self-test for resume parsing and matching, including plain-text extraction, standard headings, and job-specific checks.",
    summary: "No outside checker can reproduce every employer's configuration, but you can catch common extraction and matching problems before applying.",
    points: ["Copy the resume into a plain-text editor and inspect order and missing text.", "Check standard section headings and a clear single-column reading order.", "Avoid tables and text boxes for important information.", "Compare the resume with a real job description instead of using a generic test."],
  },
  {
    slug: "resume-keywords-not-matching-job-description",
    query: "resume keywords not matching job description",
    title: "Resume Keywords Not Matching the Job Description",
    description: "Fix resume keyword gaps by using accurate job-description phrasing, full terms and abbreviations, and stronger placement in relevant sections.",
    summary: "Keyword matching works best when the language on your resume reflects the work you have actually done and the terminology used in the target posting.",
    points: ["Use exact phrasing where it accurately describes your experience.", "Include an abbreviation and full term once when both are relevant, such as SEO and Search Engine Optimization.", "Place important terms in the summary and first bullet of each relevant role.", "Do not add a skill solely because it appears in the job description."],
  },
  {
    slug: "resume-format-issues-checklist",
    query: "resume format issues checklist",
    title: "Resume Format Issues Checklist for ATS Screening",
    description: "Use a practical checklist for tables, columns, text boxes, headings, headers, footers, and text-based PDF or DOCX resume output.",
    summary: "Formatting cannot guarantee a result, but a simple reading order reduces common ways important resume text can be missed or misread.",
    points: ["Avoid tables, multi-column layouts, and text boxes for core content.", "Keep critical contact details in the document body, not only headers or footers.", "Use standard headings such as Experience, Education, and Skills.", "Export a text-based PDF or DOCX, never a scanned image.", "Copy the final file into plain text to check extraction order."],
  },
  {
    slug: "one-page-vs-two-page-resume-ats",
    query: "one page or two page resume ats",
    title: "One-Page or Two-Page Resume for ATS Screening?",
    description: "Understand how resume length relates to ATS checks, relevance, and experience level without treating one page as a universal rule.",
    summary: "ATS checks do not directly penalize length. Relevance, readable structure, and real evidence matter more than forcing every candidate into one page.",
    points: ["Do not pad a one-page resume with vague filler.", "Use a focused two-page resume when your experience needs the space.", "Early-career candidates often have enough relevant material for one page.", "Candidates with five or more years of experience may need two pages.", "Remove repetition before removing useful evidence."],
  },
  {
    slug: "resume-file-type-pdf-vs-word-ats",
    query: "pdf or word resume for ats",
    title: "PDF or Word Resume for ATS: Which File Type?",
    description: "Compare text-based PDF and DOCX resumes for ATS use, including when to follow the job posting and how to avoid scanned files.",
    summary: "A text-based PDF generally preserves a clean layout, while some older systems may prefer DOCX. The posting's instructions should take priority.",
    points: ["Use a selectable-text PDF rather than a scanned image.", "Use DOCX when the employer or application portal specifies it.", "Open the exported file and confirm the text can be selected and copied.", "Do not assume a file extension guarantees clean parsing."],
  },
  {
    slug: "resume-parsing-errors-common-causes",
    query: "resume parsing errors common causes",
    title: "Resume Parsing Errors: Common Causes and Fixes",
    description: "Find common causes of resume parsing errors, from tables and columns to icons, text boxes, and contact details hidden in headers or footers.",
    summary: "Parsing errors occur when document structure makes it difficult to determine what text belongs together or what order it should be read in.",
    points: ["Tables and columns can confuse reading order.", "Icons and graphics carry no readable text for many parsers.", "Text boxes may be skipped when parsers read only the main text flow.", "Contact information in headers or footers can be missed.", "Use a plain-text extraction check before submitting."],
  },
  {
    slug: "fresher-resume-no-experience-ats-tips",
    query: "fresher resume no experience ats tips",
    title: "Fresher Resume with No Experience: ATS Tips",
    description: "Build an ATS-friendly fresher resume with projects, coursework, internships, measurable outcomes, and exact skills from target roles.",
    summary: "Paid employment is not the only evidence available to a fresher. Projects, coursework, internships, and practical outcomes can show relevant capability.",
    points: ["Use projects, coursework, and internships as evidence of experience.", "Quantify outcomes where the numbers are real and explainable.", "Add a dedicated skills section with accurate job-relevant terms.", "Keep the layout simple and single-column.", "Tailor the skills and project descriptions to each role."],
  },
  {
    slug: "career-switch-resume-keywords-guide",
    query: "career switch resume keywords",
    title: "Career-Switch Resume Keywords: A Practical Guide",
    description: "Translate transferable experience into the terminology of a new field without asking ATS software or recruiters to infer the connection.",
    summary: "Career-switch resumes need to make the bridge explicit. The reader should not have to translate your old industry into the new role unaided.",
    points: ["Translate relevant old-industry work into accurate new-industry terminology.", "Lead with transferable skills in the summary.", "Use exact terms from job descriptions in the new field where truthful.", "Show the result and context behind each transferable skill.", "Do not claim tools or experience you have not used."],
  },
  {
    slug: "laid-off-job-search-resume-tips",
    query: "laid off job search resume tips",
    title: "Laid-Off Job Search Resume Tips That Save Time",
    description: "Make a laid-off job search more focused with fast resume tailoring, role-specific scans, and honest application tracking.",
    summary: "A layoff can create pressure to apply everywhere. A fast, repeatable tailoring process helps preserve relevance while increasing application pace.",
    points: ["Tailor the summary and highest-value bullets first.", "Rescan the resume against each job description.", "Track versions and outcomes so urgency does not erase learning.", "Keep employment dates accurate and focus attention on current capability."],
  },
  {
    slug: "gap-in-resume-explain-ats",
    query: "how to explain employment gap on resume",
    title: "How to Explain an Employment Gap on a Resume",
    description: "Learn how to frame an employment gap briefly and honestly while keeping the resume focused on current skills and evidence.",
    summary: "An ATS does not directly judge the personal reason for a gap. Human reviewers may have questions, so a concise factual explanation is usually better than hiding the timeline.",
    points: ["Use accurate dates and do not disguise the gap.", "Add a brief factual explanation when useful, such as caregiving, study, or a sabbatical.", "Highlight skills, projects, and results you can bring to the role now.", "Keep the explanation short rather than letting it dominate the resume."],
  },
  {
    slug: "resume-tips-for-freshers-getting-shortlisted",
    query: "resume tips for freshers getting shortlisted",
    title: "Resume Tips for Freshers Getting Shortlisted",
    description: "Help a fresher resume survive quick screening with standard headings, a single-column layout, and a clear core competencies section.",
    summary: "When work history is limited, structure and relevant skills do more of the explaining. Make the strongest evidence visible before the reader has to search for it.",
    points: ["Use standard headings and a single-column layout.", "Place a focused core competencies section near the top.", "Use projects, coursework, and internships as relevant evidence.", "Write bullets with action verbs and measurable results where available.", "Match the target job's accurate terminology."],
  },
  {
    slug: "entry-level-resume-ats-friendly-guide",
    query: "entry level resume ats friendly guide",
    title: "Entry-Level Resume ATS-Friendly Guide",
    description: "Create an entry-level resume that emphasizes relevant skills and projects while keeping parsing simple and evidence specific.",
    summary: "An entry-level resume can be concise without being empty. Give skills and projects enough detail to show what you did and what changed as a result.",
    points: ["Emphasize relevant skills and projects over sparse work history.", "Use action verbs and measurable academic or personal-project results.", "Avoid creative templates that may cause parsing problems.", "Use clear headings and a readable single-column structure.", "Tailor the top section to the target role."],
  },
  {
    slug: "software-engineer-resume-keywords-ats",
    query: "software engineer resume keywords ats",
    title: "Software Engineer Resume Keywords for ATS Screening",
    description: "Choose accurate software engineering keywords by matching languages, frameworks, methodologies, and the exact technical stack in the posting.",
    summary: "Software engineering resumes need explicit technical vocabulary. Do not rely on a parser or recruiter to infer a tool from an indirect project description.",
    points: ["List languages and frameworks explicitly when you have used them.", "Include methodology terms such as Agile or Scrum when accurate.", "Match exact technology names from the job posting, including forms such as React.js.", "Separate technical skills from project evidence and outcomes.", "Never add a tool only because the role requests it."],
  },
  {
    slug: "data-analyst-resume-keywords-ats",
    query: "data analyst resume keywords ats",
    title: "Data Analyst Resume Keywords for ATS Screening",
    description: "Build a data analyst resume around explicit tools, quantified impact, and a dedicated skills section matched to the target job description.",
    summary: "Make the tools and outcomes easy to find. A recruiter should see what you used and what improved without reconstructing it from a paragraph.",
    points: ["Name tools such as SQL, Python, Tableau, and Excel when genuinely used.", "Quantify impact with accurate improvements, volume, time, or quality measures.", "Separate technical skills from soft skills.", "Mirror the job description's exact tool names where truthful.", "Connect each important tool to evidence in experience or projects."],
  },
  {
    slug: "marketing-resume-keywords-ats",
    query: "marketing resume keywords ats",
    title: "Marketing Resume Keywords for ATS Screening",
    description: "Improve a marketing resume with full terms and acronyms, grouped skills, and quantified campaign outcomes matched to the role.",
    summary: "Marketing terminology varies across employers. Use both the familiar acronym and the full term when relevant, then prove the skill with results.",
    points: ["Use full terms and acronyms, such as Search Engine Optimization (SEO).", "Group technical, marketing-specific, and soft skills clearly.", "Lead with quantified campaign, conversion, reach, or revenue results.", "Match the role's channel and methodology terms where accurate.", "Avoid keyword lists without supporting examples."],
  },
  {
    slug: "project-manager-resume-keywords-ats",
    query: "project manager resume keywords ats",
    title: "Project Manager Resume Keywords for ATS Screening",
    description: "Show project management methodology, certifications, cross-functional leadership, and quantified delivery outcomes in the employer's language.",
    summary: "Project management resumes are stronger when they connect methods and credentials to delivery evidence rather than listing them without context.",
    points: ["Include accurate methodology terms such as Agile, Scrum, or PMP.", "Write the full certification term alongside the acronym on first use when relevant.", "Quantify delivery outcomes, scope, timelines, budgets, or quality improvements.", "Use cross-functional leadership language that matches the posting.", "Separate certifications from skills and project evidence."],
  },
  {
    slug: "sales-resume-keywords-ats",
    query: "sales resume keywords ats",
    title: "Sales Resume Keywords for ATS Screening",
    description: "Strengthen a sales resume with quantified outcomes, explicit CRM tools, and the sales methodology terms used by the target employer.",
    summary: "Sales claims become more useful when the result is visible. Replace responsibility language with accurate numbers, scope, and the tools behind the work.",
    points: ["Quantify outcomes such as revenue, quota attainment, pipeline, or conversion.", "Name CRM tools such as Salesforce or HubSpot when genuinely used.", "Match the job's specific sales methodology terms where accurate.", "Lead bullets with the result, then explain the action and context.", "Do not inflate metrics or add unsupported tools."],
  },
  {
    slug: "hr-resume-keywords-ats",
    query: "hr resume keywords ats",
    title: "HR Resume Keywords for ATS Screening",
    description: "Use explicit HRIS and ATS platform names, accurate certification terms, and measurable people outcomes in an HR resume.",
    summary: "HR resumes often span systems, compliance, hiring, and people outcomes. Make each relevant area explicit and connect it to evidence.",
    points: ["Name HRIS or ATS platforms such as Workday or Greenhouse when used.", "Use full certification terms and acronyms, such as SHRM-CP, where relevant.", "Quantify retention, time-to-hire, training, or process improvements.", "Match the job description's HR terminology accurately.", "Group systems, certifications, and people skills clearly."],
  },
  {
    slug: "how-to-write-cover-letter-with-job-description",
    query: "how to write cover letter matching job description",
    title: "How to Write a Cover Letter That Matches a Job Description",
    description: "Connect your real experience to a job description with specific requirements, concise evidence, and a cover letter that does not repeat the resume.",
    summary: "A useful cover letter adds context to the application. It should show why two or three requirements connect to your experience without copying every resume bullet.",
    points: ["Mirror two or three specific requirements from the posting.", "Connect each requirement to a real example from your experience.", "Keep the letter concise and avoid repeating the resume verbatim.", "Do not add skills, companies, or numbers that are not supported by your background.", "Use the role and company name accurately."],
  },
  {
    slug: "follow-up-email-after-job-application",
    query: "follow up email after job application",
    title: "Follow-Up Email After a Job Application",
    description: "Write a short, polite application follow-up that references the role and application date without repeating a full cover letter.",
    summary: "A follow-up should make it easy for the recipient to place your application and understand why you remain interested. Brevity is part of being respectful.",
    points: ["Wait about a week unless the posting gives different instructions.", "Reference the exact role and the date you applied.", "Add one relevant reason you remain interested or qualified.", "Keep it to a few sentences rather than repeating the cover letter.", "Avoid implying that a response is owed."],
  },
  {
    slug: "how-many-jobs-should-i-apply-per-day",
    query: "how many jobs should i apply per day",
    title: "How Many Jobs Should You Apply to Per Day?",
    description: "Set a sustainable application pace by balancing job fit, resume tailoring time, and conversion tracking instead of chasing a fixed daily number.",
    summary: "There is no useful universal number. The right pace leaves enough time to choose good matches, tailor the application, and learn from the response rate.",
    points: ["Prioritize roles where your experience and requirements genuinely align.", "Allow time to tailor the resume and check its match to the posting.", "Track applications to responses rather than celebrating volume alone.", "Use conversion data to adjust your daily pace.", "Protect time for networking, preparation, and follow-up."],
  },
  {
    slug: "resume-tailoring-for-each-job-application",
    query: "should i tailor my resume for every job application",
    title: "Should You Tailor Your Resume for Every Job Application?",
    description: "Learn a fast resume-tailoring workflow: compare the job, adjust accurate keywords and evidence, then rescan before applying.",
    summary: "Tailoring does not mean rewriting from scratch. It means making the most relevant, truthful evidence easy to find for this particular role.",
    points: ["Compare your resume with the specific job description.", "Adjust accurate keywords, summary language, and the strongest bullets.", "Keep claims, numbers, and experience truthful.", "Rescan the tailored version before submitting it.", "Save versions so you can track what works."],
  },
];

export const SEO_GUIDE_BY_SLUG = Object.fromEntries(
  SEO_GUIDES.map((guide) => [guide.slug, guide]),
) as Record<string, SeoGuide>;
